local languages = {
    ["english"] = {
        ["not_allow_cmd"] = "You are not allowed to use this command!",
        ["not_perm"] = "You don't have the permission to do this!",
        ["save_setting"] = "Settings Sucessfully Saved.",
        ["new_setting_received"] = "LinvLib : New Settings Received.",
        ["in_dev"] = "Fonctionality in development.",
        ["invalid_value"] = "Invalid Value",
        ["background"] = "Background",
        ["border"] = "Border",
        ["element"] = "Element",
        ["accent"] = "Accent",
        ["hover"] = "Hover",
        ["text"] = "Text",
        ["icon"] = "Icon",
        ["red"] = "Red",
        ["close"] = "Close",
        ["continue"] = "Continue",
        ["reset"] = "Reset",
        ["customisation"] = "Customisation",
        ["border_size"] = "Border Size",
        ["rounded"] = "Rounded Value",
        ["other"] = "Others",
        ["debug_mode"] = "Debug Mode",
        ["settings"] = "Settings",
        ["global_ban"] = "Global Ban",
        ["linventif_security"] = "Linventif Security",
        ["admin_group"] = "Admin Groups",
        ["admin_ticket"] = "Ticket Admin",
        ["admin_menu_extend"] = "Admin Menu Extended",
        ["admin_menu"] = "Admin Menu",
        ["admin_suite"] = "Admin Suite",
        ["show_if_new_addon"] = "Show if new addon is detected",
        ["show_if_need_update"] = "Show if addon need update",
        ["show_at_every_join"] = "Show at every join",
        ["monitor"] = "Monitor",
        ["theme"] = "Theme",
        ["compatible_addon"] = "Compatible Addon",
        ["language"] = "Language",
        ["general"] = "General",
        ["ply_trust_factor"] = "Player Trust Factor",
        ["ply_trust_factor_min"] = "Minimum Acceptable Trust Factor",
        ["language_add"] = "To add custom language contact me on discord !",
        ["theme_add"] = "To add custom theme contact me on discord !",
        ["help"] = "Help",
        ["install_addon"] = "Addons Installed : ",
        ["addon_need_update"] = "Addon Need Update : ",
        ["linventif_lib"] = "Linventif's Stuff",
        ["new_addon_detected"] = "New Addon Detected : ",
        ["new_addon"] = "New Addon",
        ["name"] = "Name",
        ["your_version"] = "Your Version",
        ["last_version"] = "Last Version",
        ["link"] = "Link",
        ["update"] = "Update",
        ["open"] = "Open",
    },
    ["french"] = {
        ["not_allow_cmd"] = "Vous n'êtes pas autorisé à utiliser cette commande !",
        ["not_perm"] = "Vous n'avez pas la permission de faire cela !",
        ["save_setting"] = "Paramètres Sauvegardés Avec Succès.",
        ["new_setting_received"] = "LinvLib : Nouveaux Paramètres Reçus.",
        ["in_dev"] = "Fonctionnalité en développement.",
        ["invalid_value"] = "Valeur Invalide",
        ["background"] = "Fond",
        ["border"] = "Bordure",
        ["element"] = "Élément",
        ["accent"] = "Accent",
        ["hover"] = "Survol",
        ["text"] = "Texte",
        ["icon"] = "Icône",
        ["red"] = "Rouge",
        ["close"] = "Fermer",
        ["continue"] = "Continuer",
        ["reset"] = "Réinitialiser",
        ["customisation"] = "Personnalisation",
        ["border_size"] = "Taille de la Bordure",
        ["rounded"] = "Valeur Arrondie",
        ["other"] = "Autres",
        ["debug_mode"] = "Mode Debug",
        ["settings"] = "Paramètres",
        ["global_ban"] = "Ban Globale",
        ["linventif_security"] = "Sécurité Linventif",
        ["admin_group"] = "Groupes Admin",
        ["admin_ticket"] = "Ticket Admin",
        ["admin_menu_extend"] = "Menu Admin Étendu",
        ["admin_menu"] = "Menu Admin",
        ["admin_suite"] = "Suite Admin",
        ["show_if_new_addon"] = "Afficher si un nouveau addon est détecté",
        ["show_if_need_update"] = "Afficher si un addon a besoin d'une mise à jour",
        ["show_at_every_join"] = "Afficher à chaque connexion",
        ["monitor"] = "Moniteur",
        ["theme"] = "Thème",
        ["compatible_addon"] = "Addon Compatible",
        ["language"] = "Langue",
        ["general"] = "Général",
        ["ply_trust_factor"] = "Trust Factor Joueur",
        ["ply_trust_factor_min"] = "Trust Factor Minimum Acceptable",
        ["language_add"] = "Pour ajouter une langue custom contactez moi sur discord !",
        ["theme_add"] = "Pour ajouter un thème custom contactez moi sur discord !",
        ["help"] = "Aide",
        ["install_addon"] = "Addon Installés : ",
        ["addon_need_update"] = "Addon Nécessitant Une Mise à Jour : ",
        ["linventif_lib"] = "Trucs Linventif",
        ["new_addon_detected"] = "Nouvel Addon Détecté : ",
        ["new_addon"] = "Nouvel Addon",
        ["name"] = "Nom",
        ["your_version"] = "Votre Version",
        ["last_version"] = "Dernière Version",
        ["link"] = "Lien",
        ["update"] = "Mettre à Jour",
        ["open"] = "Ouvrir",
    },
}

// -- // -- // -- // -- // -- // -- // -- //
// DO NOT EDIT BELOW THIS LINE
// -- // -- // -- // -- // -- // -- // -- //

function LinvLib:GetTrad(id)
    if languages[LinvLib.Config.Language] && languages[LinvLib.Config.Language][id] then
        return languages[LinvLib.Config.Language][id]
    else
        return languages["english"][id] || id
    end
end

function LinvLib:GetLanguageId()
    local tbl = {}
    for k, v in pairs(languages) do
        table.insert(tbl, k)
    end
    return tbl
end